name: Run API Automation with Newman

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: "30 4 * * *"   # 10:00 AM IST (04:30 UTC)

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

		  - name: Debug workspace
		    run: |
		      echo "Current directory:"
		      pwd
		      echo "Files in workspace:"
		      ls -la

		  - name: Run Newman and generate report
		    run: |
		      mkdir -p reports
		      newman run ./on_Arrival.postman_collection.json \
		      -r htmlextra \
		      --reporter-htmlextra-export reports/report.html || true

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "API Automation Report - Newman"
          body: |
            Hi Team,

            Please find attached the latest Newman API automation report.

            Regards,
            QA Team
          to: sachin.pujari@credilio.in, saswat.chaturvedi@credilio.in
          from: QA Automation
          attachments: reports/report.html
